<<<<<<< HEAD
permalink: /:title

title: BeiYuu.com
url: http://nuoer.site
feed: /atom.xml
author_info: <a href="http://nuoer.site/">BeiYuu</a>
=======
theme: jekyll-theme-cayman
>>>>>>> 87f179104996164b5a058040896c56d79e010147
